import { format } from "date-fns";
import type { HighCourtAttempt, HighCourtGroupedResult } from "@/lib/highCourt";

const safe = (value: unknown) =>
  String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");

function paperPage(
  result: HighCourtGroupedResult,
  attempt: HighCourtAttempt,
  label: string,
  maximum: number,
) {
  const alignment = attempt.alignment || [];
  const totalOriginalWords = alignment.filter((entry) => entry.original && entry.original !== "[[PARA]]").length;
  const totalWordsTyped = alignment.filter((entry) => entry.typed && entry.typed !== "[[PARA]]").length;
  const missingWords = alignment.filter((entry) => entry.status === "missing").length;
  const rows = alignment.map((entry) => {
    const expected = entry.original
      ? `<span class="success">[${safe(entry.original)}]</span>`
      : "";

    if (entry.status === "missing") {
      return `<span class="success">[${safe(entry.original)}]</span> `;
    }

    if (entry.status === "match") {
      return `<span>${safe(entry.typed)}</span> `;
    }

    return `<span class="error">${safe(entry.typed || "—")}</span> ${expected} `;
  }).join("");

  return `
    <section class="report-page">
      <h1>Pragati Institute of Professional Studies</h1>
      <p class="subtitle">Kalindipuram, Prayagraj, 211011</p>
      <p class="subtitle">Contact No: 9026212705</p>
      <h2>Test Result Report</h2>

      <table>
        <tr>
          <td class="label">Student Name:</td><td>${safe(result.studentName)}</td>
          <td class="label">Student ID:</td><td>${safe(result.studentDisplayId || result.studentId)}</td>
        </tr>
        <tr>
          <td class="label">Test Folder:</td><td>${safe(result.testSetTitle)}</td>
          <td class="label">Date:</td><td>${format(new Date(attempt.submittedAt), "PPP p")}</td>
        </tr>
        <tr>
          <td class="label">Paper:</td><td>${safe(label)}</td>
          <td class="label">Test Duration:</td><td>High Court Assessment</td>
        </tr>
      </table>

      <h3>Performance Metrics</h3>
      <table class="metrics-table">
        <tr>
          <th>Metric</th><th>Value</th><th>Metric</th><th>Value</th>
        </tr>
        <tr>
          <td>Total Original Words</td><td>${totalOriginalWords}</td>
          <td>Total Words Attempted</td><td>${totalWordsTyped}</td>
        </tr>
        <tr>
          <td>Full Mistakes</td><td class="error">${safe(attempt.mistakes)}</td>
          <td>Half Mistakes</td><td class="error">${safe(attempt.halfMistakes)}</td>
        </tr>
        <tr>
          <td>Missing Words</td><td class="error">${missingWords}</td>
          <td>Marks Obtained</td><td class="success">${safe(attempt.marks)} / ${maximum}</td>
        </tr>
      </table>

      <h3>Typed Content (Errors Underlined)</h3>
      <div class="content-box">${rows || "No comparison detail available."}</div>

      <div class="footer">
        Generated by Pragati Institute Portal • ${format(new Date(), "PPP")}
      </div>
    </section>
  `;
}

export function downloadHighCourtPdf(result: HighCourtGroupedResult) {
  const attemptedPages = [
    result.typing ? paperPage(result, result.typing, "Typing Test", 100) : "",
    result.pitman ? paperPage(result, result.pitman, "Pitman Test", 100) : "",
    result.shorthand ? paperPage(result, result.shorthand, "Shorthand Test", 200) : "",
  ].join("");

  if (!attemptedPages) return;

  const iframe = document.createElement("iframe");
  iframe.style.position = "fixed";
  iframe.style.right = "0";
  iframe.style.bottom = "0";
  iframe.style.width = "0";
  iframe.style.height = "0";
  iframe.style.border = "0";
  document.body.appendChild(iframe);

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${safe(result.testSetTitle)} — High Court Result</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 6px; color: #000; background: #fff; }
        @media print {
          body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
          @page { size: A4; margin: 8mm; }
        }
        .report-page { min-height: 260mm; page-break-after: always; }
        .report-page:last-child { page-break-after: auto; }
        h1 { color: #1e3a8a; font-size: 20px; margin: 0 0 2px 0; text-align: center; }
        p.subtitle { text-align: center; color: #555; margin: 0 0 8px 0; font-size: 12px; }
        h2 { font-size: 18px; border-bottom: 1px solid #ddd; padding-bottom: 4px; margin-top: 8px; margin-bottom: 8px; text-align: center; }
        h3 { font-size: 16px; margin: 16px 0 6px 0; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 8px; font-size: 14px; }
        td { padding: 4px 6px; vertical-align: top; }
        .label { font-weight: bold; width: 100px; }
        .metrics-table th, .metrics-table td { border: 1px solid #ddd; padding: 6px; text-align: left; }
        .metrics-table th { background-color: #f8fafc; }
        .content-box { padding: 4px; background-color: #fff; border-radius: 4px; line-height: 1.4; margin-bottom: 6px; font-size: 12px; overflow-wrap: anywhere; }
        .error { color: #dc2626; font-weight: bold; text-decoration: underline; text-decoration-thickness: 2px; }
        .success { color: #15803d; font-weight: bold; }
        .footer { text-align: center; font-size: 10px; color: #999; margin-top: 40px; border-top: 1px solid #eee; padding-top: 10px; }
      </style>
    </head>
    <body>${attemptedPages}</body>
    </html>
  `;

  const doc = iframe.contentWindow?.document;
  if (!doc) {
    document.body.removeChild(iframe);
    return;
  }

  doc.open();
  doc.write(htmlContent);
  doc.close();

  setTimeout(() => {
    iframe.contentWindow?.focus();
    iframe.contentWindow?.print();
    setTimeout(() => {
      if (document.body.contains(iframe)) {
        document.body.removeChild(iframe);
      }
    }, 60000);
  }, 500);
}